RESULT = polytype.exe
LIBS =
SOURCES = \
	store.ml \
	const.ml \
	context.ml \
	absyn.ml \
	prims.ml \
	core.ml \
	parser.mly \
	lexer.mll \
	error.ml \
	main.ml

OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
